import 'react';
import './Provider/ThemeContext.js';
import 'classnames';
import { css } from '@emotion/css';
import { css as css$1 } from '@emotion/react';
import '@emotion/styled';
import { a as _taggedTemplateLiteralLoose } from './_rollupPluginBabelHelpers.js';
import './ColorMode/ColorModeContext.js';
import './utils/cssProps.js';
import 'lodash/kebabCase';
import 'tinycolor2';
import { L as breakpoint, k as theme, p as borderRadius } from './getCSSFromStyleObject.js';
import 'lodash/uniq';
import 'reakit/Id';
import 'deepmerge';
import 'lodash/set';
import 'lodash/get';
import 'capsize';
import './utils/gradient.js';
import '@emotion/is-prop-valid';
import './utils/OutsideClickHandler.js';

var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14, _templateObject15, _templateObject16, _templateObject17, _templateObject18, _templateObject19, _templateObject20, _templateObject21, _templateObject22;
var Group = function Group(styleProps) {
  return css(_templateObject || (_templateObject = _taggedTemplateLiteralLoose(["\n  flex-direction: ", ";\n\n  ", ";\n\n  && > * {\n    border-radius: 0px;\n    ", ";\n  }\n\n  & input,\n  & select {\n    border-radius: 0px;\n\n    &:focus {\n      z-index: 1;\n      position: relative;\n    }\n  }\n\n  & > *:first-child {\n    ", "\n\n    & input,\n    & select {\n      ", ";\n    }\n\n    ", ";\n  }\n\n  & > *:last-child {\n    ", "\n\n    & input,\n    & select {\n      ", ";\n    }\n\n    ", ";\n  }\n\n  & > *:not(:first-child):not(:last-child),\n  & > *:not(:first-child):not(:last-child) > input,\n  & > *:not(:first-child):not(:last-child) > select {\n    border-radius: 0;\n    ", ";\n  }\n\n  & > *:not(:first-child) {\n    ", "\n  }\n\n  & {\n    ", ";\n  }\n"])), styleProps.orientation === 'vertical' ? 'column' : 'row', breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject2 || (_templateObject2 = _taggedTemplateLiteralLoose(["\n      flex-direction: column;\n    "]))))(styleProps), theme(styleProps.themeKey, "Item.styles.base")(styleProps), styleProps.orientation === 'vertical' ? css$1(_templateObject3 || (_templateObject3 = _taggedTemplateLiteralLoose(["\n            border-top-right-radius: ", ";\n            border-top-left-radius: ", ";\n          "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)) : css$1(_templateObject4 || (_templateObject4 = _taggedTemplateLiteralLoose(["\n            ", ";\n          "])), breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject5 || (_templateObject5 = _taggedTemplateLiteralLoose(["\n                border-top-right-radius: ", ";\n                border-top-left-radius: ", ";\n              "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)), {
    else: css$1(_templateObject6 || (_templateObject6 = _taggedTemplateLiteralLoose(["\n                  border-bottom-left-radius: ", ";\n                  border-top-left-radius: ", ";\n                "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps))
  })(styleProps)), styleProps.orientation === 'vertical' ? css$1(_templateObject7 || (_templateObject7 = _taggedTemplateLiteralLoose(["\n              border-top-right-radius: ", ";\n              border-top-left-radius: ", ";\n            "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)) : css$1(_templateObject8 || (_templateObject8 = _taggedTemplateLiteralLoose(["\n              ", ";\n            "])), breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject9 || (_templateObject9 = _taggedTemplateLiteralLoose(["\n                  border-top-right-radius: ", ";\n                  border-top-left-radius: ", ";\n                "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)), {
    else: css$1(_templateObject10 || (_templateObject10 = _taggedTemplateLiteralLoose(["\n                    border-bottom-left-radius: ", ";\n                    border-top-left-radius: ", ";\n                  "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps))
  })(styleProps)), theme(styleProps.themeKey, "Item.styles.first")(styleProps), styleProps.orientation === 'vertical' ? css$1(_templateObject11 || (_templateObject11 = _taggedTemplateLiteralLoose(["\n            border-bottom-right-radius: ", ";\n            border-bottom-left-radius: ", ";\n          "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)) : css$1(_templateObject12 || (_templateObject12 = _taggedTemplateLiteralLoose(["\n            ", ";\n          "])), breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject13 || (_templateObject13 = _taggedTemplateLiteralLoose(["\n                border-bottom-left-radius: ", ";\n                border-bottom-right-radius: ", ";\n              "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)), {
    else: css$1(_templateObject14 || (_templateObject14 = _taggedTemplateLiteralLoose(["\n                  border-top-right-radius: ", ";\n                  border-bottom-right-radius: ", ";\n                "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps))
  })(styleProps)), styleProps.orientation === 'vertical' ? css$1(_templateObject15 || (_templateObject15 = _taggedTemplateLiteralLoose(["\n              border-bottom-left-radius: ", ";\n              border-bottom-right-radius: ", ";\n            "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)) : css$1(_templateObject16 || (_templateObject16 = _taggedTemplateLiteralLoose(["\n              ", ";\n            "])), breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject17 || (_templateObject17 = _taggedTemplateLiteralLoose(["\n                  border-bottom-left-radius: ", ";\n                  border-bottom-right-radius: ", ";\n                "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps)), {
    else: css$1(_templateObject18 || (_templateObject18 = _taggedTemplateLiteralLoose(["\n                    border-top-right-radius: ", ";\n                    border-bottom-right-radius: ", ";\n                  "])), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps), borderRadius(styleProps.borderRadius, styleProps.borderRadius)(styleProps))
  })(styleProps)), theme(styleProps.themeKey, "Item.styles.last")(styleProps), theme(styleProps.themeKey, "Item.styles.middle")(styleProps), styleProps.orientation === 'vertical' ? css$1(_templateObject19 || (_templateObject19 = _taggedTemplateLiteralLoose(["\n            border-top-width: 0;\n          "]))) : css$1(_templateObject20 || (_templateObject20 = _taggedTemplateLiteralLoose(["\n            ", ";\n          "])), breakpoint(styleProps.verticalBelow ? "max-" + styleProps.verticalBelow : null, css$1(_templateObject21 || (_templateObject21 = _taggedTemplateLiteralLoose(["\n                border-top-width: 0;\n              "]))), {
    else: css$1(_templateObject22 || (_templateObject22 = _taggedTemplateLiteralLoose(["\n                  border-left-width: 0;\n                "])))
  })(styleProps)), theme(styleProps.themeKey, "styles.base")(styleProps));
};

var Group_styles = /*#__PURE__*/Object.freeze({
  __proto__: null,
  Group: Group
});

export { Group_styles as G, Group as a };
